###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog post tetst 5",
    "author": "Ron Wesley",
    "url": "http://google.com/blog_test_5",
    "likes": 0,
    "userId": "6059bc0400fbec5321456cde"
}

###

DELETE http://localhost:3003/api/blogs/604c68003b1a790bbbd40a22

###
PUT http://localhost:3003/api/blogs/604c68063b1a790bbbd40a23
Content-Type: application/json

{
    "title": "Blog post tetst 5",
    "author": "no two",
    "url": "",
    "likes": 15
}




###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hagrid",
    "name": "Hagrid"
}

