###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Blog post tetst 4",
    "author": "no one",
    "url": "",
    "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/604c68003b1a790bbbd40a22

###
PUT http://localhost:3003/api/blogs/604c68063b1a790bbbd40a23
Content-Type: application/json

{
    "title": "Blog post tetst 5",
    "author": "no two",
    "url": "",
    "likes": 15
}
