###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog post tetst 4",
    "author": "no one",
    "url": "",
    "likes": 0
}

###

